import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight:["400","500","600","700","800"   ]
})
const inter = Inter({
  variable: "--font-inter",
  subsets:["latin"], 
  weight: ["400","500","600","700","800","900"]
})

export const metadata: Metadata = {
  title: "Finta - Startup  Accounting and Taxes",
  description: "Generated by create next app",
  icons:{
    icon: "/finta-icon-light.svg"
  }
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased [--pattern-fg:var(--color-neutral-950)]/[0.02] dark:[--pattern-fg:var(--color-neutral-50)]/10`}
      >
        <ThemeProvider attribute={"class"} enableSystem defaultTheme="system">
        {/* <main className="bg-background text-foreground h-screen">{children}</main> */}
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
